### ISSUE TITLE
Do we have plan to integrate DepthPro model?

### ISSUE THREAD

**Issue by tufeixp** [thygate/stable-diffusion-webui-depthmap-script#475]
https://huggingface.co/apple/DepthPro

https://github.com/spacepxl/ComfyUI-Depth-Pro

**Comment by graemeniedermayer** [comment]
hmm I was concerned about the weird licenses. Are both the licenses to avoid liability?

**Comment by tufeixp** [comment]
> hmm I was concerned about the weird licenses. Are both the licenses to avoid liability?

Looks fine:
https://developer.apple.com/support/downloads/terms/apple-sample-code/Apple-Sample-Code-License.pdf

**Comment by graemeniedermayer** [comment]
So there's some difficult with integration because it uses an older version of `timm` so it breaks other models.

I made a branch that includes it here
https://github.com/graemeniedermayer/stable-diffusion-webui-normalmap-script/tree/depthpro

For my usage, it actually doesn't seem an improvement over high resolution depthanything v2 (depthanything v2 left, depthpro right)
![comparison](https://github.com/user-attachments/assets/9ebb6575-fcf0-485f-9ffe-fbdea17be4f9)
