### ISSUE TITLE
script installed but doesn't show up in scripts...

### ISSUE THREAD

**Issue by amirrrr234** [thygate/stable-diffusion-webui-depthmap-script#86]
hello. 
i used to work with depth map script for a month but in the past week after installing the script in web ui, depth map doesnt show up in the scripts menu of img2img or text2img tabs.
i know its installed already and its shown in installed tab and the extension folder is in the directory.
(and i didnt forget to restart the ui).
how can i use the script?
thanks for helping

**Comment by thygate** [comment]
Check the console output when starting the webui, is there an error message ?

**Comment by amirrrr234** [comment]
thanks for your support
the last lines of the console that seemed to be an error are these:
2023-01-11T10:11:16.748691318Z A matching Triton is not available, some optimizations will not be enabled.
2023-01-11T10:11:16.748737758Z Error caught was: No module named 'triton'

**Comment by graemeniedermayer** [comment]
This sounds like a Stable Diffusion problem specifically --xformers uses Triton. I ran into a similar problem when I switched to v2.1.

If I remember correctly the solution was to manual install Triton with `pip install triton`. It's a math optimization library.

https://triton-lang.org/master/getting-started/installation.html

**Comment by LanceGao97** [comment]
To create a public link, set `share=True` in `launch()`.
Create LRU cache (max_size=16) for preprocessor results.
Startup time: 6.3s (load scripts: 2.0s, create ui: 1.7s, gradio launch: 2.4s, scripts app_started_callback: 0.1s).
Error completing request
Arguments: ('https://github.com/thygate/stable-diffusion-webui-depthmap-script.git', [], 0, '') {}
Traceback (most recent call last):
  File "/root/stable-diffusion-webui/modules/call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "/root/stable-diffusion-webui/modules/ui_extensions.py", line 373, in install_extension_from_index
    ext_table, message = install_extension_from_url(None, url)
  File "/root/stable-diffusion-webui/modules/ui_extensions.py", line 343, in install_extension_from_url
    with git.Repo.clone_from(url, tmpdir) as repo:
  File "/root/stable-diffusion-webui/venv/lib/python3.10/site-packages/git/repo/base.py", line 1325, in clone_from
    return cls._clone(
  File "/root/stable-diffusion-webui/venv/lib/python3.10/site-packages/git/repo/base.py", line 1234, in _clone
    finalize_process(proc, stderr=stderr)
  File "/root/stable-diffusion-webui/venv/lib/python3.10/site-packages/git/util.py", line 419, in finalize_process
    proc.wait(**kwargs)
  File "/root/stable-diffusion-webui/venv/lib/python3.10/site-packages/git/cmd.py", line 604, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v -- https://github.com/thygate/stable-diffusion-webui-depthmap-script.git /root/stable-diffusion-webui/tmp/stable-diffusion-webui-depthmap-script
  stderr: 'Cloning into '/root/stable-diffusion-webui/tmp/stable-diffusion-webui-depthmap-script'...
POST git-upload-pack (177 bytes)
error: RPC failed; curl 56 GnuTLS recv error (-9): Error decoding the received TLS packet.
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
'

**Comment by LanceGao97** [comment]
This is on a jupiter server,  it don't show DepthScript Tab after install from url,

**Comment by jasoncow007** [comment]
> This sounds like a Stable Diffusion problem specifically --xformers uses Triton. I ran into a similar problem when I switched to v2.1.
> 
> If I remember correctly the solution was to manual install Triton with `pip install triton`. It's a math optimization library.
> 
> https://triton-lang.org/master/getting-started/installation.html

cannot find a version,,,,how to install the triton
pip install triton
ERROR: Could not find a version that satisfies the requirement triton (from versions: none)
ERROR: No matching distribution found for triton
