### ISSUE TITLE
Unable to install rembg which prevents SD Web UI to start

### ISSUE THREAD

**Issue by Harvester62** [thygate/stable-diffusion-webui-depthmap-script#89]
After today's update, I am unable to start SD Web UI due to an issue with this Extension installation, possibly due to rembg, as per attached screenshot of the Windows console.
I am on Windows 10 Pro, with SD Web UI Commit hash: 97ff69eff338c6641f4abf430bf5ac112c1775e0

The extension was working fine yesterday. Please, have a look at these errors, thank you. I need to have all the extensions activated to properly translate the Web UI, Scripts and Extensions for the Italian Localization.

![immagine](https://user-images.githubusercontent.com/29801031/211859666-38997ea2-8bd0-4ace-b214-cb8638927b25.png)

**Comment by Harvester62** [comment]
Hmmm, perhaps it's not your extension's faul but Dreambooth instead. Still checking.

**Comment by graemeniedermayer** [comment]
As a quick test, while your venv is active, do you get the same error with a manual `pip3 install rembg` or `pip install rembg`?  I wasn't expecting permission issues from rembg. 

I'm a little confused by the `-illow` error, that looks like a typo on `Pillow`. Is that a regular flag you get or do you think it's related?

To me, it looks like it's failed while switching to Pillow from 9.4.0 to 9.3.0 (for context 9.4.0 was released on Jan 2 2023).

**Comment by Harvester62** [comment]
After moving the Dreambooth extension's folder away from the SD Web UI installation (to another location) and restarting I was still getting errors, even about the model not being loaded, so I deleted the config.json file (sometimes it helps) and restarted. Then the rembg was installed together with other two requirements and this confirms that your extension is fine. The rembg is now inside the C:\stable-diffusion-webui\venv\Lib\site-packages directory. Those -illow are for some reasons copies of the already existing Pillow dependency, very strange, but I think I can simply delete these strange folders, some starts like this: ~illow-9.3.0. 
Anyway, I was a little scared when I saw the permission issues because I have admin privileges for my account in Windows, but as I said, probably the problem was in the config.json file. Now, I restarted everything and re-installed Dreambooth and reinstated the required command line arguments in webui-user.bat:

set "REQS_FILE=.\extensions\sd_dreambooth_extension\requirements.txt"
set DREAMBOOTH_SKIP_INSTALL=True
set ACCELERATE="True"

Now everything seem to work again, so for sure the config.json was a source of problems, plus I had to deactivate the ABG_extenstion as well as the Detection Detailer because they give me problems (the DD seems to make any generation to be "A photograph of a donkey", which is funny but useless, I thing is some sort or debug thing).

So, sorry for the false alarm about your extension which works fine. You can close this bug report.

**Comment by TernaryM01** [comment]
@Harvester62 No, I'm having the same issue, and it's certainly caused by installing this extension @thygate. That's a false false alarm!

I run and re-run WebUI all day without issues or weird messages in the prompt. But as soon as I installed this extension, it says cannot install rembg because of OSError: Access denied. I closed WebUI, deleted the extension, changed the permission of the whole content of my venv folder to everybody having Full Control, and then relaunched WebUI. Then I saw messages saying:
`WARNING: Ignoring invalid distribution -illow`
and other nonsensical corrupt package names.
Then I tried to install this extension again, but got the same error.

I realized that "Access denied" has nothing to do with lack of permission, but rather, python is trying to install/access packages with corrupt names such as "-illow". The source of the problem might be the config of **this extension,** not WebUI or Dreambooth.

I want to stress out again that this has nothing to do with the Dreambooth extension, as I've never touched or used it at all (or installed any Dreambooth-related extension) since I installed the WebUI.

**Comment by graemeniedermayer** [comment]
I'm pretty sure it's not that the packages are corrupt. It's trying to reinstall packages that are current being used. It comes up with Pillow in particular because rembg uses Pillow 9.3 whereas auto1111 uses Pillow 9.4 .

I was kind of hoping that rembg would be updated, but maybe forking rembg and updating the requirement file would help resolve this.

**Comment by TernaryM01** [comment]
@graemeniedermayer Makes sense, thanks for the explanation!

I've ended up opting for the other script: "depthmap2mask". I was simply looking for a way to generate a depth map for any image with dpt-large (the most accurate model), and this other script does the job.

**Comment by SoundGuy** [comment]
I'm also having the same issue when installing:

stderr: Traceback (most recent call last):
  File "G:\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\install.py", line 16, in <module>
    launch.run_pip("install rembg", "rembg requirement for depthmap script")
  File "g:\stable-diffusion-webui\launch.py", line 137, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "g:\stable-diffusion-webui\launch.py", line 105, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install rembg requirement for depthmap script.
Command: "g:\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install rembg --prefer-binary

**Comment by SoundGuy** [comment]
also seeing this at the end

Requirement already satisfied: pyreadline3 in .\venv\lib\site-packages (from humanfriendly>=9.1->coloredlogs->onnxruntime~=1.13.1->rembg) (3.4.1)
Installing collected packages: pillow, numpy, humanfriendly, starlette, scipy, pooch, opencv-python-headless, coloredlogs, asyncer, scikit-image, pymatting, onnxruntime, imagehash, fastapi, rembg
  Attempting uninstall: pillow
    Found existing installation: Pillow 9.4.0
    Uninstalling Pillow-9.4.0:
      Successfully uninstalled Pillow-9.4.0

stderr: WARNING: Ignoring invalid distribution -illow (g:\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (g:\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (g:\stable-diffusion-webui\venv\lib\site-packages)
    WARNING: Ignoring invalid distribution -illow (g:\stable-diffusion-webui\venv\lib\site-packages)
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'G:\\stable-diffusion-webui\\venv\\Lib\\site-packages\\~-l\\_imaging.cp310-win_amd64.pyd'
Check the permissions.

WARNING: Ignoring invalid distribution -illow (g:\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (g:\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (g:\stable-diffusion-webui\venv\lib\site-packages)

**Comment by graemeniedermayer** [comment]
Maybe it is a good idea to have a to have a local version of rembg which should solve these issues.

I think it would be an exact clone except for in line 11 of `https://github.com/danielgatis/rembg/blob/main/requirements.txt` 

`pillow==9.3.0`
would become
`pillow>=9.3.0` or `pillow==9.4.0`

That should stop the error that starts with
```
Attempting uninstall: pillow
Found existing installation: Pillow 9.4.0
Uninstalling Pillow-9.4.0:
```

**Comment by SoundGuy** [comment]
> Maybe it is a good idea to have a to have a local version of rembg which should solve these issues.

how do i tell pip to install it from a local modified copy?

**Comment by semjon00** [comment]
Very probably fixed as for now.
